version: '3'

services:
  cmds_editor:
    restart: unless-stopped
    image: "nginx"
    volumes:
        - ./source:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html

    ports:
      - "3000:80"
